export interface Spacecraft {
  id: string;
  name: string;
  agency: string;
  agencyFull: string;
  country: string;
  type: string;
  launchYear: number;
  status: string;
  mission: string;
  description: string;
  features: string[];
  dimensions?: string;
  mass?: string;
  destination?: string;
  notableAchievements: string[];
  modelUrl?: string;
  imageColor: string;
  category: "crewed" | "robotic" | "satellite" | "probe" | "telescope" | "station" | "lander";
}

export const spacecraftData: Spacecraft[] = [
  // NASA
  {
    id: "apollo-11",
    name: "Apollo 11",
    agency: "NASA",
    agencyFull: "National Aeronautics and Space Administration",
    country: "USA",
    type: "Crewed Spacecraft",
    launchYear: 1969,
    status: "Retired",
    mission: "First crewed Moon landing",
    description: "Apollo 11 was the spaceflight that first landed humans on the Moon. Commander Neil Armstrong and lunar module pilot Buzz Aldrin formed the American crew that landed the Apollo Lunar Module Eagle on July 20, 1969.",
    features: ["Command Module Columbia", "Lunar Module Eagle", "Saturn V rocket", "Fuel cells for power"],
    dimensions: "Height: 110.6 m (Saturn V), CM: 3.9 m diameter",
    mass: "2,800 kg (CM)",
    destination: "Moon",
    notableAchievements: ["First humans on Moon", "Neil Armstrong's first step", "393 kg of lunar samples", "Historic radio transmission"],
    imageColor: "#1a3a5c",
    category: "crewed"
  },
  {
    id: "voyager-1",
    name: "Voyager 1",
    agency: "NASA",
    agencyFull: "National Aeronautics and Space Administration",
    country: "USA",
    type: "Space Probe",
    launchYear: 1977,
    status: "Active",
    mission: "Interstellar exploration",
    description: "Voyager 1 is a space probe launched by NASA on September 5, 1977. It is the farthest human-made object from Earth. As of 2024, it is more than 24 billion km from Earth, operating in interstellar space.",
    features: ["Radioisotope thermoelectric generators", "High-gain antenna", "Golden Record", "Scientific instruments"],
    dimensions: "3.7 m diameter dish antenna",
    mass: "825.5 kg",
    destination: "Interstellar Space",
    notableAchievements: ["Farthest human-made object", "First spacecraft in interstellar space", "Discovered Jupiter's rings", "Detailed images of Saturn"],
    imageColor: "#2d5016",
    category: "probe"
  },
  {
    id: "hubble",
    name: "Hubble Space Telescope",
    agency: "NASA/ESA",
    agencyFull: "NASA & European Space Agency",
    country: "USA/Europe",
    type: "Space Telescope",
    launchYear: 1990,
    status: "Active",
    mission: "Deep space observation",
    description: "The Hubble Space Telescope is a large, space-based observatory launched into low Earth orbit. It has made over 1.5 million observations and helped determine the age of the universe.",
    features: ["2.4-meter primary mirror", "Advanced Camera for Surveys", "Wide Field Camera 3", "UV, visible, near-IR imaging"],
    dimensions: "13.1 m long, 4.2 m diameter",
    mass: "11,110 kg",
    destination: "Low Earth Orbit (559 km)",
    notableAchievements: ["Determined universe age: 13.8 billion years", "Discovered dark energy evidence", "Ultra Deep Field images", "Over 1.5 million observations"],
    imageColor: "#1a1a6e",
    category: "telescope"
  },
  {
    id: "perseverance",
    name: "Perseverance Rover",
    agency: "NASA",
    agencyFull: "National Aeronautics and Space Administration",
    country: "USA",
    type: "Mars Rover",
    launchYear: 2020,
    status: "Active",
    mission: "Mars exploration & astrobiology",
    description: "Perseverance is a car-sized Mars rover exploring Jezero Crater. It is searching for signs of ancient microbial life, collecting rock samples for future return to Earth, and testing oxygen production from Mars's atmosphere.",
    features: ["MOXIE oxygen production", "Ingenuity helicopter", "SHERLOC Raman spectrometer", "PIXL X-ray spectrometer"],
    dimensions: "3 m long, 2.7 m wide, 2.2 m tall",
    mass: "1,025 kg",
    destination: "Mars (Jezero Crater)",
    notableAchievements: ["First flight on another planet (Ingenuity)", "MOXIE oxygen production", "42+ rock samples cached", "First audio recordings on Mars"],
    imageColor: "#8B4513",
    category: "robotic"
  },
  {
    id: "iss",
    name: "International Space Station",
    agency: "NASA/ESA/Roscosmos/JAXA/CSA",
    agencyFull: "Multi-Agency Partnership",
    country: "International",
    type: "Space Station",
    launchYear: 1998,
    status: "Active",
    mission: "Microgravity research platform",
    description: "The ISS is a modular space station in low Earth orbit. A multinational collaborative project, it serves as a microgravity research laboratory. The station has been continuously occupied since November 2000.",
    features: ["16 pressurized modules", "8 pairs of solar arrays", "Canadarm2 robotic arm", "Multiple docking ports"],
    dimensions: "109 m × 73 m × 27 m",
    mass: "420,000 kg",
    destination: "Low Earth Orbit (408 km)",
    notableAchievements: ["Continuously crewed since 2000", "3,000+ scientific experiments", "250+ visitors from 20 countries", "1 million+ hours of research"],
    imageColor: "#4a4a8a",
    category: "station"
  },
  {
    id: "space-shuttle",
    name: "Space Shuttle Columbia",
    agency: "NASA",
    agencyFull: "National Aeronautics and Space Administration",
    country: "USA",
    type: "Reusable Spacecraft",
    launchYear: 1981,
    status: "Retired",
    mission: "First reusable space vehicle",
    description: "The Space Shuttle was NASA's reusable launch system. Columbia was the first shuttle to fly in space (1981) and completed 27 missions before the tragic accident on February 1, 2003.",
    features: ["Reusable orbiter", "External fuel tank", "Two solid rocket boosters", "Payload bay"],
    dimensions: "Orbiter: 37.2 m long",
    mass: "68,585 kg (orbiter)",
    destination: "Low Earth Orbit",
    notableAchievements: ["First reusable spacecraft", "Launched Hubble", "Chandra X-ray Observatory deployment", "37 years of shuttle program"],
    imageColor: "#c0c0c0",
    category: "crewed"
  },
  {
    id: "jwst",
    name: "James Webb Space Telescope",
    agency: "NASA/ESA/CSA",
    agencyFull: "NASA, ESA & Canadian Space Agency",
    country: "USA/Europe/Canada",
    type: "Space Telescope",
    launchYear: 2021,
    status: "Active",
    mission: "Deep universe infrared observation",
    description: "The James Webb Space Telescope is the largest and most powerful space telescope ever built. It observes in infrared light, allowing it to see the first stars and galaxies that formed after the Big Bang.",
    features: ["6.5-meter beryllium mirror", "18 hexagonal mirror segments", "Infrared imaging", "L2 orbit position"],
    dimensions: "22 m × 12 m deployed",
    mass: "6,500 kg",
    destination: "L2 Lagrange Point (1.5M km)",
    notableAchievements: ["Deepest infrared image of universe", "Exoplanet atmosphere analysis", "First galaxies after Big Bang", "CO2 on exoplanet detected"],
    imageColor: "#FFD700",
    category: "telescope"
  },
  {
    id: "cassini",
    name: "Cassini-Huygens",
    agency: "NASA/ESA/ASI",
    agencyFull: "NASA, ESA & Italian Space Agency",
    country: "USA/Europe/Italy",
    type: "Orbiter + Lander",
    launchYear: 1997,
    status: "Retired (2017)",
    mission: "Saturn system exploration",
    description: "Cassini was a spacecraft sent to study Saturn and its moons. It orbited Saturn for 13 years and delivered the Huygens probe to Titan. It ended its mission by diving into Saturn's atmosphere in 2017.",
    features: ["Huygens probe", "Radar altimeter", "Imaging Science Subsystem", "Ion and neutral mass spectrometer"],
    dimensions: "6.7 m tall",
    mass: "5,712 kg",
    destination: "Saturn & its moons",
    notableAchievements: ["Discovered Enceladus ocean", "Titan surface images", "340,000+ images", "Water plumes on Enceladus"],
    imageColor: "#DAA520",
    category: "probe"
  },
  {
    id: "new-horizons",
    name: "New Horizons",
    agency: "NASA",
    agencyFull: "National Aeronautics and Space Administration",
    country: "USA",
    type: "Space Probe",
    launchYear: 2006,
    status: "Active",
    mission: "Pluto & Kuiper Belt exploration",
    description: "New Horizons is a NASA space probe that performed a six-month reconnaissance flyby of Pluto in 2015, sending back the first detailed images and data of the dwarf planet system.",
    features: ["Alice UV spectrometer", "RALPH camera", "REX radio experiment", "LORRI long-range camera"],
    dimensions: "2.1 m × 2.7 m × 3.2 m",
    mass: "478 kg",
    destination: "Pluto & Kuiper Belt",
    notableAchievements: ["First flyby of Pluto", "Heart-shaped feature discovered", "Charon close-up images", "Kuiper Belt Objects study"],
    imageColor: "#4169E1",
    category: "probe"
  },
  // ESA
  {
    id: "rosetta",
    name: "Rosetta",
    agency: "ESA",
    agencyFull: "European Space Agency",
    country: "Europe",
    type: "Comet Orbiter",
    launchYear: 2004,
    status: "Retired (2016)",
    mission: "Comet 67P exploration",
    description: "Rosetta was an ESA space probe that performed a detailed study of comet 67P/Churyumov–Gerasimenko. It deployed the Philae lander – the first spacecraft to land on a comet nucleus.",
    features: ["Philae lander", "12 scientific instruments", "Solar panels", "Navigation cameras"],
    dimensions: "2.8 m × 2.1 m × 2.0 m body",
    mass: "2,900 kg",
    destination: "Comet 67P",
    notableAchievements: ["First comet landing (Philae)", "Water ice detected on comet", "Organic molecules found", "Comet's shape revealed"],
    imageColor: "#228B22",
    category: "probe"
  },
  {
    id: "mars-express",
    name: "Mars Express",
    agency: "ESA",
    agencyFull: "European Space Agency",
    country: "Europe",
    type: "Mars Orbiter",
    launchYear: 2003,
    status: "Active",
    mission: "Mars atmosphere & surface study",
    description: "Mars Express is ESA's first planetary mission. It has been orbiting Mars since December 2003 and provides detailed images and data about Mars's surface, atmosphere and geological history.",
    features: ["HRSC stereo camera", "MARSIS subsurface radar", "Beagle 2 lander (lost)", "Spectrometers"],
    dimensions: "1.5 m × 1.8 m × 1.4 m",
    mass: "1,223 kg",
    destination: "Mars Orbit",
    notableAchievements: ["Discovered subsurface water ice", "2+ million images taken", "Methane detection", "Longest ESA planetary mission"],
    imageColor: "#8B0000",
    category: "probe"
  },
  // Roscosmos / Soviet
  {
    id: "sputnik-1",
    name: "Sputnik 1",
    agency: "Soviet Space Program",
    agencyFull: "Soviet Union Space Program",
    country: "USSR",
    type: "Satellite",
    launchYear: 1957,
    status: "Deorbited (1958)",
    mission: "First Earth satellite",
    description: "Sputnik 1 was the first artificial Earth satellite. The Soviet Union launched it into an elliptical low Earth orbit on October 4, 1957, starting the Space Age and the Space Race.",
    features: ["Radio transmitter", "Four external radio antennas", "Pressurized nitrogen sphere", "Thermal control system"],
    dimensions: "58 cm diameter sphere",
    mass: "83.6 kg",
    destination: "Low Earth Orbit",
    notableAchievements: ["First artificial satellite", "Began the Space Age", "Sparked the Space Race", "Orbited Earth 1,440 times"],
    imageColor: "#8B8B00",
    category: "satellite"
  },
  {
    id: "soyuz",
    name: "Soyuz Spacecraft",
    agency: "Roscosmos",
    agencyFull: "Russian Federal Space Agency (Roscosmos)",
    country: "Russia",
    type: "Crewed Spacecraft",
    launchYear: 1967,
    status: "Active",
    mission: "Crew transport to ISS",
    description: "Soyuz is a series of spacecraft designed for the Soviet space program. It is the longest-serving crewed spacecraft design in history. Soyuz ferries cosmonauts and astronauts to and from the ISS.",
    features: ["Three modules (orbital, descent, service)", "Solar panels", "Docking system", "Parachute landing system"],
    dimensions: "7.2 m long, 2.72 m diameter",
    mass: "7,250 kg",
    destination: "Low Earth Orbit / ISS",
    notableAchievements: ["Oldest operational crewed spacecraft", "70+ crew rotations to ISS", "Near-perfect safety record", "Only ISS crew transport 2011-2020"],
    imageColor: "#006400",
    category: "crewed"
  },
  {
    id: "luna-9",
    name: "Luna 9",
    agency: "Soviet Space Program",
    agencyFull: "Soviet Union Space Program",
    country: "USSR",
    type: "Moon Lander",
    launchYear: 1966,
    status: "Retired",
    mission: "First soft landing on Moon",
    description: "Luna 9 was an uncrewed Soviet spacecraft that achieved the first successful soft landing on the Moon on February 3, 1966. It transmitted photographic data from the lunar surface.",
    features: ["Television camera system", "Four petal-like panels", "Radiation detector", "Radio transmitter"],
    dimensions: "58 cm diameter (lander)",
    mass: "99 kg (lander)",
    destination: "Moon (Ocean of Storms)",
    notableAchievements: ["First soft landing on Moon", "First photos from lunar surface", "Proved surface stability", "9 panoramic images"],
    imageColor: "#B8860B",
    category: "lander"
  },
  // ISRO
  {
    id: "chandrayaan-3",
    name: "Chandrayaan-3",
    agency: "ISRO",
    agencyFull: "Indian Space Research Organisation",
    country: "India",
    type: "Moon Lander & Rover",
    launchYear: 2023,
    status: "Mission Complete",
    mission: "Lunar south pole soft landing",
    description: "Chandrayaan-3 is the third Indian lunar exploration mission. It successfully landed on the Moon's south polar region on August 23, 2023, making India the fourth country to land on the Moon and first at the south pole.",
    features: ["Vikram lander", "Pragyan rover", "Spectro-polarimetry instrument", "LIBS & APXS instruments"],
    dimensions: "Lander: 2 m × 2 m × 1.17 m",
    mass: "3,900 kg total",
    destination: "Moon South Pole Region",
    notableAchievements: ["First south pole landing", "India's 4th Moon landing country", "Sulfur detected on Moon", "Water ice evidence"],
    imageColor: "#FF6600",
    category: "lander"
  },
  {
    id: "mangalyaan",
    name: "Mangalyaan (MOM)",
    agency: "ISRO",
    agencyFull: "Indian Space Research Organisation",
    country: "India",
    type: "Mars Orbiter",
    launchYear: 2013,
    status: "Retired (2022)",
    mission: "Mars orbit insertion demonstration",
    description: "Mars Orbiter Mission (Mangalyaan) was India's first interplanetary mission. It made India the first Asian country to reach Mars orbit and only country to succeed on its maiden attempt.",
    features: ["Five scientific instruments", "Color camera", "Methane sensor", "Thermal infrared spectrometer"],
    dimensions: "1.5 m × 1.5 m × 1.5 m",
    mass: "1,337 kg",
    destination: "Mars Orbit",
    notableAchievements: ["First Indian Mars mission", "First Asian Mars orbit", "Success on first attempt", "₹450 crore budget (cheapest Mars mission)"],
    imageColor: "#FF4500",
    category: "probe"
  },
  // JAXA
  {
    id: "hayabusa2",
    name: "Hayabusa2",
    agency: "JAXA",
    agencyFull: "Japan Aerospace Exploration Agency",
    country: "Japan",
    type: "Asteroid Sample Return",
    launchYear: 2014,
    status: "Active (extended mission)",
    mission: "Asteroid Ryugu sample return",
    description: "Hayabusa2 is a Japanese asteroid sample-return mission. It visited asteroid Ryugu, collected samples using a touch-and-go method, and successfully returned them to Earth in December 2020.",
    features: ["Kinetic impactor", "MINERVA-II rovers", "MASCOT lander", "Sample collection horn"],
    dimensions: "1.0 m × 1.6 m × 1.25 m",
    mass: "609 kg",
    destination: "Asteroid Ryugu",
    notableAchievements: ["First subsurface asteroid sample", "Organic materials found", "4 small landers deployed", "Artificial crater created"],
    imageColor: "#9370DB",
    category: "probe"
  },
  // SpaceX
  {
    id: "dragon",
    name: "SpaceX Dragon (Crew Dragon)",
    agency: "SpaceX",
    agencyFull: "Space Exploration Technologies Corp",
    country: "USA (Private)",
    type: "Commercial Crew Spacecraft",
    launchYear: 2020,
    status: "Active",
    mission: "Commercial crew transport to ISS",
    description: "Crew Dragon is a private spacecraft developed by SpaceX. It carries astronauts to and from the ISS and is part of NASA's Commercial Crew Program. It is the first commercial spacecraft to carry humans to the ISS.",
    features: ["Touch-screen controls", "SuperDraco abort engines", "Reusable design", "Autonomous docking"],
    dimensions: "8.1 m tall, 4 m diameter",
    mass: "12,519 kg",
    destination: "Low Earth Orbit / ISS",
    notableAchievements: ["First private crewed spacecraft to ISS", "Multiple successful crew rotations", "Splashdown recovery system", "Inspiration4 all-civilian mission"],
    imageColor: "#2F4F4F",
    category: "crewed"
  },
  {
    id: "starship",
    name: "SpaceX Starship",
    agency: "SpaceX",
    agencyFull: "Space Exploration Technologies Corp",
    country: "USA (Private)",
    type: "Super Heavy-Lift Launch Vehicle",
    launchYear: 2023,
    status: "Development",
    mission: "Mars colonization & Moon missions",
    description: "Starship is a fully reusable two-stage rocket system being developed by SpaceX. It is designed to carry humans and cargo to the Moon, Mars, and beyond. It is the largest and most powerful rocket ever built.",
    features: ["Super Heavy booster", "Raptor engines", "Stainless steel construction", "Full reusability"],
    dimensions: "121 m tall (total)",
    mass: "5,000,000 kg (full stack)",
    destination: "Moon, Mars, Deep Space",
    notableAchievements: ["Most powerful rocket ever built", "NASA Artemis lunar lander selected", "Booster catch with mechanical arms", "First integrated flight tests"],
    imageColor: "#C0C0C0",
    category: "crewed"
  },
  // CNSA
  {
    id: "tianwen-1",
    name: "Tianwen-1",
    agency: "CNSA",
    agencyFull: "China National Space Administration",
    country: "China",
    type: "Mars Orbiter, Lander & Rover",
    launchYear: 2020,
    status: "Active",
    mission: "Mars orbit, surface exploration",
    description: "Tianwen-1 is China's first independent Mars mission. It successfully entered Mars orbit in February 2021 and deployed the Zhurong rover on the surface, making China the second country to successfully operate a rover on Mars.",
    features: ["Zhurong rover", "7 scientific instruments", "Orbiter + lander combo", "Ground-penetrating radar"],
    dimensions: "Rover: 1.85 m long",
    mass: "5,000 kg total",
    destination: "Mars (Utopia Planitia)",
    notableAchievements: ["China's first Mars landing", "Zhurong rover deployed", "1,921 meters traversed", "Subsurface radar survey"],
    imageColor: "#DC143C",
    category: "robotic"
  }
];

export const agencies = [
  { name: "NASA", country: "USA", founded: 1958, missions: "500+", color: "#0B3D91", flag: "🇺🇸" },
  { name: "ESA", country: "Europe", founded: 1975, missions: "100+", color: "#003299", flag: "🇪🇺" },
  { name: "Roscosmos", country: "Russia", founded: 1992, missions: "1800+", color: "#003DA5", flag: "🇷🇺" },
  { name: "ISRO", country: "India", founded: 1969, missions: "100+", color: "#FF6600", flag: "🇮🇳" },
  { name: "JAXA", country: "Japan", founded: 2003, missions: "50+", color: "#0E4FA0", flag: "🇯🇵" },
  { name: "CNSA", country: "China", founded: 1993, missions: "200+", color: "#DE2910", flag: "🇨🇳" },
  { name: "SpaceX", country: "USA (Private)", founded: 2002, missions: "250+", color: "#2F4F4F", flag: "🚀" },
];
