export interface Spacecraft {
  id: string;
  name: string;
  agency: string;
  type: string;
  era: string;
  destination: string;
  crewed: boolean;
  status: 'active' | 'completed' | 'planned' | 'cancelled';
  launchYear: number;
  description: string;
  specs: { label: string; value: string }[];
  funFacts: string[];
  crew?: string[];
  sketchfabId?: string;
  youtubeId?: string;
  nasaQuery: string;
  relatedMissions: string[];
  timeline: { year: number; event: string }[];
}

export const spacecraftData: Spacecraft[] = [
  // NASA
  {
    id: 'mercury',
    name: 'Mercury Capsule',
    agency: 'NASA',
    type: 'Crewed Capsule',
    era: '1960s',
    destination: 'Earth Orbit',
    crewed: true,
    status: 'completed',
    launchYear: 1958,
    description: 'America\'s first human spaceflight program that put the first Americans in space. Six astronauts flew suborbital and orbital missions between 1961 and 1963.',
    specs: [
      { label: 'Height', value: '2.9 m' },
      { label: 'Diameter', value: '1.89 m' },
      { label: 'Mass', value: '1,355 kg' },
      { label: 'Crew', value: '1 astronaut' },
      { label: 'Missions', value: '20 total (6 crewed)' },
    ],
    funFacts: ['John Glenn became first American to orbit Earth in Mercury Atlas 6', 'Capsule was so small astronauts said they "wore" it', 'Alan Shepard made America\'s first spaceflight on May 5, 1961'],
    crew: ['Alan Shepard', 'Gus Grissom', 'John Glenn', 'Scott Carpenter', 'Wally Schirra', 'Gordon Cooper'],
    youtubeId: 'quzf5EZ1IGA',
    nasaQuery: 'Mercury capsule space program',
    relatedMissions: ['Gemini', 'Apollo'],
    timeline: [
      { year: 1958, event: 'Mercury program initiated' },
      { year: 1961, event: 'First US crewed spaceflight — Alan Shepard' },
      { year: 1962, event: 'John Glenn orbits Earth 3 times' },
      { year: 1963, event: 'Gordon Cooper\'s 22-orbit final Mercury mission' },
    ],
  },
  {
    id: 'gemini',
    name: 'Gemini Spacecraft',
    agency: 'NASA',
    type: 'Crewed Capsule',
    era: '1960s',
    destination: 'Earth Orbit',
    crewed: true,
    status: 'completed',
    launchYear: 1961,
    description: 'Bridge between Mercury and Apollo, Gemini perfected spacewalking, orbital rendezvous, and docking — essential skills for reaching the Moon.',
    specs: [
      { label: 'Height', value: '5.8 m' },
      { label: 'Diameter', value: '3.05 m' },
      { label: 'Mass', value: '3,851 kg' },
      { label: 'Crew', value: '2 astronauts' },
      { label: 'Missions', value: '12 (10 crewed)' },
    ],
    funFacts: ['First American spacewalk by Ed White in Gemini IV', 'Developed techniques critical for Moon landing', 'First space rendezvous by Gemini VI and VII'],
    crew: ['Gus Grissom', 'John Young', 'Ed White', 'Pete Conrad', 'Neil Armstrong'],
    youtubeId: 'N4Yto3g96uE',
    nasaQuery: 'Gemini spacecraft program NASA',
    relatedMissions: ['Mercury', 'Apollo'],
    timeline: [
      { year: 1961, event: 'Gemini program approved' },
      { year: 1965, event: 'First US spacewalk — Gemini IV' },
      { year: 1965, event: 'First orbital rendezvous — Gemini VI & VII' },
      { year: 1966, event: 'Final Gemini mission (XII)' },
    ],
  },
  {
    id: 'apollo',
    name: 'Apollo Spacecraft',
    agency: 'NASA',
    type: 'Lunar Spacecraft',
    era: '1960s–1970s',
    destination: 'Moon',
    crewed: true,
    status: 'completed',
    launchYear: 1967,
    description: 'The spacecraft that carried humanity to the Moon. 12 astronauts walked on the lunar surface across 6 successful landings between 1969 and 1972.',
    specs: [
      { label: 'Command Module Height', value: '3.9 m' },
      { label: 'Diameter', value: '3.9 m' },
      { label: 'Mass', value: '28,803 kg total' },
      { label: 'Crew', value: '3 astronauts' },
      { label: 'Duration', value: 'Up to 12.5 days' },
    ],
    funFacts: ['12 humans have walked on the Moon, all via Apollo', '"One small step for man" — Neil Armstrong, July 20 1969', 'Apollo 13 was "a successful failure" — crew rescued from Moon disaster'],
    crew: ['Neil Armstrong', 'Buzz Aldrin', 'Michael Collins', 'Jim Lovell', 'Alan Shepard', 'Edgar Mitchell'],
    sketchfabId: '5e5a7af73e5a4f19897e5ddddad96440',
    youtubeId: 'S9HdPi9Ikhk',
    nasaQuery: 'Apollo Moon landing spacecraft',
    relatedMissions: ['Gemini', 'Space Shuttle', 'Artemis'],
    timeline: [
      { year: 1967, event: 'Apollo 1 tragedy — 3 astronauts lost' },
      { year: 1968, event: 'Apollo 8 — First humans to orbit Moon' },
      { year: 1969, event: 'Apollo 11 — First Moon landing' },
      { year: 1970, event: 'Apollo 13 — Near-fatal abort' },
      { year: 1972, event: 'Apollo 17 — Last Moon mission' },
    ],
  },
  {
    id: 'shuttle',
    name: 'Space Shuttle',
    agency: 'NASA',
    type: 'Reusable Orbiter',
    era: '1980s–2000s',
    destination: 'Earth Orbit',
    crewed: true,
    status: 'completed',
    launchYear: 1981,
    description: 'The world\'s first reusable spacecraft, flying 135 missions over 30 years. Built the ISS, deployed and repaired Hubble, and transformed human spaceflight.',
    specs: [
      { label: 'Length', value: '56.1 m' },
      { label: 'Wingspan', value: '23.8 m' },
      { label: 'Mass', value: '68,585 kg (orbiter)' },
      { label: 'Crew', value: 'Up to 8 astronauts' },
      { label: 'Payload to LEO', value: '24,400 kg' },
    ],
    funFacts: ['5 orbiters built: Columbia, Challenger, Discovery, Atlantis, Endeavour', 'Challenger and Columbia tragedies killed 14 astronauts', 'Hubble Space Telescope was deployed and serviced by Shuttle'],
    crew: ['Christa McAuliffe', 'Sally Ride', 'John Young', 'Robert Crippen'],
    youtubeId: 'OnoNITE-CLc',
    nasaQuery: 'Space Shuttle NASA orbiter',
    relatedMissions: ['ISS', 'Hubble', 'Apollo'],
    timeline: [
      { year: 1981, event: 'First Shuttle flight — Columbia STS-1' },
      { year: 1986, event: 'Challenger disaster' },
      { year: 1990, event: 'Hubble Space Telescope deployed' },
      { year: 2003, event: 'Columbia disaster' },
      { year: 2011, event: 'Final Shuttle mission — Atlantis STS-135' },
    ],
  },
  {
    id: 'hubble',
    name: 'Hubble Space Telescope',
    agency: 'NASA/ESA',
    type: 'Space Telescope',
    era: '1990s–Present',
    destination: 'Earth Orbit',
    crewed: false,
    status: 'active',
    launchYear: 1990,
    description: 'Orbiting at 547 km altitude, Hubble has transformed our understanding of the cosmos with over 1.5 million observations spanning 30+ years.',
    specs: [
      { label: 'Length', value: '13.2 m' },
      { label: 'Diameter', value: '4.27 m' },
      { label: 'Mass', value: '11,110 kg' },
      { label: 'Altitude', value: '547 km' },
      { label: 'Orbital Period', value: '95 minutes' },
    ],
    funFacts: ['Initial mirror defect was corrected in 1993 by Space Shuttle astronauts', 'Determined the universe is 13.8 billion years old', 'Observed stars and galaxies 13.4 billion light-years away'],
    youtubeId: 'aTrHOi8bkxE',
    nasaQuery: 'Hubble Space Telescope images',
    relatedMissions: ['James Webb Telescope', 'Space Shuttle'],
    timeline: [
      { year: 1990, event: 'Launched aboard Space Shuttle Discovery' },
      { year: 1993, event: 'Mirror corrected by Shuttle servicing mission' },
      { year: 2009, event: 'Final servicing mission extends life' },
      { year: 2021, event: 'Gyroscope issue resolved' },
    ],
  },
  {
    id: 'voyager1',
    name: 'Voyager 1',
    agency: 'NASA',
    type: 'Interstellar Probe',
    era: '1970s–Present',
    destination: 'Interstellar Space',
    crewed: false,
    status: 'active',
    launchYear: 1977,
    description: 'Humanity\'s most distant spacecraft, Voyager 1 has traveled beyond the solar system and into interstellar space, still transmitting data after 46+ years.',
    specs: [
      { label: 'Mass', value: '721.9 kg' },
      { label: 'Distance (2024)', value: '23+ billion km' },
      { label: 'Speed', value: '61,500 km/h' },
      { label: 'Power', value: 'RTG plutonium generators' },
      { label: 'Signal Delay', value: '22+ hours one-way' },
    ],
    funFacts: ['Carries a Golden Record with Earth sounds for any alien finders', 'Entered interstellar space in 2012', 'Will take 40,000 years to reach another star system'],
    youtubeId: 'oU4xKJvX_4M',
    nasaQuery: 'Voyager 1 spacecraft interstellar',
    relatedMissions: ['Voyager 2', 'New Horizons'],
    timeline: [
      { year: 1977, event: 'Launched September 5, 1977' },
      { year: 1979, event: 'Jupiter flyby — detailed images' },
      { year: 1980, event: 'Saturn flyby — reveals ring structure' },
      { year: 1990, event: 'Pale Blue Dot photograph' },
      { year: 2012, event: 'Enters interstellar space' },
    ],
  },
  {
    id: 'voyager2',
    name: 'Voyager 2',
    agency: 'NASA',
    type: 'Interstellar Probe',
    era: '1970s–Present',
    destination: 'Interstellar Space',
    crewed: false,
    status: 'active',
    launchYear: 1977,
    description: 'The only spacecraft to have visited all four outer planets — Jupiter, Saturn, Uranus, and Neptune. Now in interstellar space.',
    specs: [
      { label: 'Mass', value: '721.9 kg' },
      { label: 'Launch Date', value: 'Aug 20, 1977' },
      { label: 'Speed', value: '55,346 km/h' },
      { label: 'Outer Planets Visited', value: '4 (unique to V2)' },
    ],
    funFacts: ['Only probe to fly past Neptune and Uranus', 'Discovered geysers on Neptune\'s moon Triton', 'Entered interstellar space in 2018'],
    youtubeId: 'oU4xKJvX_4M',
    nasaQuery: 'Voyager 2 outer planets',
    relatedMissions: ['Voyager 1', 'New Horizons'],
    timeline: [
      { year: 1977, event: 'Launched August 20, 1977' },
      { year: 1979, event: 'Jupiter flyby' },
      { year: 1981, event: 'Saturn flyby' },
      { year: 1986, event: 'Uranus flyby — first ever' },
      { year: 1989, event: 'Neptune flyby — first ever' },
      { year: 2018, event: 'Enters interstellar space' },
    ],
  },
  {
    id: 'curiosity',
    name: 'Curiosity Rover',
    agency: 'NASA',
    type: 'Mars Rover',
    era: '2010s–Present',
    destination: 'Mars',
    crewed: false,
    status: 'active',
    launchYear: 2011,
    description: 'Car-sized nuclear-powered rover that landed in Gale Crater in 2012. Confirmed Mars had conditions suitable for microbial life billions of years ago.',
    specs: [
      { label: 'Mass', value: '899 kg' },
      { label: 'Length', value: '2.9 m' },
      { label: 'Power', value: 'RTG nuclear generator' },
      { label: 'Speed', value: '0.14 km/h max' },
      { label: 'Distance Driven', value: '32+ km' },
    ],
    funFacts: ['Used sky crane landing — lowered by rocket-powered descent stage', 'Has a laser for vaporizing rocks for analysis', 'Confirmed Mars once had liquid water'],
    youtubeId: 'P4boyXQuUIw',
    nasaQuery: 'Curiosity Mars rover Gale crater',
    relatedMissions: ['Perseverance', 'Mars Pathfinder', 'Opportunity'],
    timeline: [
      { year: 2011, event: 'Launch' },
      { year: 2012, event: 'Successful landing in Gale Crater' },
      { year: 2013, event: 'Confirms Mars had habitable ancient lake' },
      { year: 2016, event: 'Climbs Mount Sharp' },
      { year: 2024, event: 'Still operational — 12 years on Mars' },
    ],
  },
  {
    id: 'perseverance',
    name: 'Perseverance Rover',
    agency: 'NASA',
    type: 'Mars Rover',
    era: '2020s–Present',
    destination: 'Mars',
    crewed: false,
    status: 'active',
    launchYear: 2020,
    description: 'NASA\'s most sophisticated Mars rover, actively collecting samples for future return to Earth while searching for signs of ancient life in Jezero Crater.',
    specs: [
      { label: 'Mass', value: '1,025 kg' },
      { label: 'Length', value: '3 m' },
      { label: 'Power', value: 'RTG nuclear' },
      { label: 'Cameras', value: '23 total' },
      { label: 'Microphones', value: '2 (first on Mars)' },
    ],
    funFacts: ['Deployed Ingenuity — first powered flight on another planet', 'Made oxygen from Martian CO2 with MOXIE', 'Carries Mars sample tubes for future Earth return'],
    youtubeId: 'vzFMFZBYSo0',
    nasaQuery: 'Perseverance rover Mars Jezero crater',
    relatedMissions: ['Curiosity', 'Ingenuity', 'Mars Sample Return'],
    timeline: [
      { year: 2020, event: 'Launch — July 30, 2020' },
      { year: 2021, event: 'Landing in Jezero Crater — Feb 18, 2021' },
      { year: 2021, event: 'Ingenuity makes first powered Mars flight' },
      { year: 2022, event: 'First core samples collected' },
    ],
  },
  {
    id: 'jwst',
    name: 'James Webb Space Telescope',
    agency: 'NASA/ESA/CSA',
    type: 'Space Telescope',
    era: '2020s–Present',
    destination: 'L2 Lagrange Point',
    crewed: false,
    status: 'active',
    launchYear: 2021,
    description: 'The most powerful space telescope ever built, JWST observes the universe in infrared revealing the first galaxies, exoplanet atmospheres, and more.',
    specs: [
      { label: 'Mirror Diameter', value: '6.5 m (18 segments)' },
      { label: 'Mass', value: '6,161 kg' },
      { label: 'Distance from Earth', value: '1.5 million km (L2)' },
      { label: 'Wavelengths', value: 'Near to mid-infrared' },
      { label: 'Operating Temperature', value: '-233°C' },
    ],
    funFacts: ['Mirror unfolds like a flower after launch — could not fit in rocket closed', 'Can detect heat of a bumblebee on the Moon', 'Cost ~$10 billion — 30 years in development'],
    youtubeId: 'dCyHsMV5mAI',
    nasaQuery: 'James Webb Space Telescope images galaxies',
    relatedMissions: ['Hubble', 'Spitzer', 'Roman Telescope'],
    timeline: [
      { year: 1996, event: 'JWST project begins' },
      { year: 2021, event: 'Launch on Ariane 5 — Dec 25, 2021' },
      { year: 2022, event: 'First images released' },
      { year: 2023, event: 'Exoplanet atmosphere discoveries' },
    ],
  },
  {
    id: 'orion',
    name: 'Orion Spacecraft',
    agency: 'NASA',
    type: 'Deep Space Capsule',
    era: '2020s–Present',
    destination: 'Moon/Deep Space',
    crewed: true,
    status: 'active',
    launchYear: 2022,
    description: 'NASA\'s next-generation crew vehicle designed to carry astronauts beyond the Moon and eventually to Mars as part of the Artemis program.',
    specs: [
      { label: 'Height', value: '3.3 m (crew module)' },
      { label: 'Diameter', value: '5.03 m' },
      { label: 'Mass', value: '25,848 kg' },
      { label: 'Crew', value: 'Up to 4 astronauts' },
      { label: 'Max Duration', value: '21 days' },
    ],
    funFacts: ['Heat shield largest ever built at 5m diameter', 'Tested with Artemis I uncrewed 2022 Moon flyby', 'Artemis II will carry crew around Moon in 2025'],
    youtubeId: '3RN4mFYQnHw',
    nasaQuery: 'Orion spacecraft Artemis Moon',
    relatedMissions: ['Apollo', 'SLS', 'Lunar Gateway'],
    timeline: [
      { year: 2011, event: 'Orion development begins' },
      { year: 2014, event: 'Exploration Flight Test-1' },
      { year: 2022, event: 'Artemis I — uncrewed Moon mission' },
      { year: 2025, event: 'Artemis II — first crewed flight planned' },
    ],
  },
  {
    id: 'crew-dragon',
    name: 'Crew Dragon',
    agency: 'SpaceX/NASA',
    type: 'Crewed Capsule',
    era: '2020s–Present',
    destination: 'Earth Orbit (ISS)',
    crewed: true,
    status: 'active',
    launchYear: 2020,
    description: 'SpaceX\'s fully autonomous spacecraft that restored US human spaceflight capability, regularly ferrying astronauts to the International Space Station.',
    specs: [
      { label: 'Height', value: '8.1 m (with trunk)' },
      { label: 'Diameter', value: '4 m' },
      { label: 'Mass', value: '12,519 kg' },
      { label: 'Crew', value: 'Up to 7 astronauts' },
      { label: 'Reusability', value: 'Multiple missions' },
    ],
    funFacts: ['First commercial spacecraft to carry NASA astronauts', 'Launches on Falcon 9 rocket — both are reusable', 'Has launched 40+ astronauts including private missions'],
    crew: ['Doug Hurley', 'Bob Behnken', 'Mike Hopkins'],
    youtubeId: 'xY96v0OIcig',
    nasaQuery: 'SpaceX Crew Dragon ISS launch',
    relatedMissions: ['Falcon 9', 'ISS', 'Starship'],
    timeline: [
      { year: 2019, event: 'Uncrewed Demo-1 to ISS' },
      { year: 2020, event: 'Demo-2 — first crewed commercial spaceflight' },
      { year: 2020, event: 'Crew-1 — first operational mission' },
      { year: 2021, event: 'Inspiration4 — first all-civilian orbital mission' },
    ],
  },
  // SOVIET/RUSSIA
  {
    id: 'sputnik',
    name: 'Sputnik 1',
    agency: 'USSR',
    type: 'Satellite',
    era: '1950s',
    destination: 'Earth Orbit',
    crewed: false,
    status: 'completed',
    launchYear: 1957,
    description: 'The world\'s first artificial satellite, Sputnik\'s launch on October 4, 1957 initiated the Space Age and the Space Race between the US and USSR.',
    specs: [
      { label: 'Diameter', value: '58.5 cm' },
      { label: 'Mass', value: '83.6 kg' },
      { label: 'Orbital Period', value: '96.2 minutes' },
      { label: 'Altitude', value: '577 km apogee' },
      { label: 'Operational Life', value: '3 weeks' },
    ],
    funFacts: ['Its radio signal "beep beep" was heard worldwide', 'Orbited Earth 1,440 times before re-entering', 'Triggered the US to create NASA in 1958'],
    youtubeId: 'CcivDhSBMgI',
    nasaQuery: 'Sputnik satellite 1957',
    relatedMissions: ['Vostok', 'Explorer 1'],
    timeline: [
      { year: 1957, event: 'Launch — October 4, 1957' },
      { year: 1957, event: 'US public in shock — Space Race begins' },
      { year: 1958, event: 'Re-enters atmosphere — mission ends' },
    ],
  },
  {
    id: 'vostok',
    name: 'Vostok 1',
    agency: 'USSR',
    type: 'Crewed Capsule',
    era: '1960s',
    destination: 'Earth Orbit',
    crewed: true,
    status: 'completed',
    launchYear: 1961,
    description: 'Vostok 1 carried Yuri Gagarin on humanity\'s first spaceflight on April 12, 1961, completing a single orbit of Earth in 108 minutes.',
    specs: [
      { label: 'Diameter', value: '2.3 m' },
      { label: 'Mass', value: '4,725 kg' },
      { label: 'Crew', value: '1 cosmonaut' },
      { label: 'Duration', value: '108 minutes' },
      { label: 'Orbits', value: '1' },
    ],
    funFacts: ['Gagarin ejected and parachuted separately from capsule at 7km altitude', '"Poyekhali!" (Let\'s go!) — Gagarin\'s famous words at launch', 'Gagarin was 27 years old during the flight'],
    crew: ['Yuri Gagarin'],
    youtubeId: 'mhMvBuJvDMU',
    nasaQuery: 'Vostok Gagarin first spaceflight',
    relatedMissions: ['Sputnik', 'Soyuz', 'Mercury'],
    timeline: [
      { year: 1961, event: 'April 12 — Gagarin becomes first human in space' },
      { year: 1961, event: 'Returns safely to Earth' },
    ],
  },
  {
    id: 'soyuz',
    name: 'Soyuz Spacecraft',
    agency: 'Roscosmos',
    type: 'Crewed Capsule',
    era: '1960s–Present',
    destination: 'Earth Orbit (ISS)',
    crewed: true,
    status: 'active',
    launchYear: 1967,
    description: 'The world\'s most reliable crewed spacecraft with 150+ missions. Served as the sole crew transport to the ISS for nearly a decade.',
    specs: [
      { label: 'Length', value: '7.48 m' },
      { label: 'Mass', value: '7,250 kg' },
      { label: 'Crew', value: '3 cosmonauts' },
      { label: 'Duration', value: 'Up to 6 months docked' },
      { label: 'Reliability', value: '98%+ success rate' },
    ],
    funFacts: ['Flew from 1967 to present — longest-running crewed spacecraft', 'Was the only crew transport to ISS from 2011-2020', 'Lands on steppes of Kazakhstan with parachute and retro-rockets'],
    youtubeId: 'bZe5J8SVCYQ',
    nasaQuery: 'Soyuz spacecraft ISS docking',
    relatedMissions: ['ISS', 'Mir', 'Vostok'],
    timeline: [
      { year: 1967, event: 'First flight — Soyuz 1 (fatal crash)' },
      { year: 1975, event: 'Apollo-Soyuz joint mission' },
      { year: 1998, event: 'ISS construction support begins' },
      { year: 2024, event: 'Still operational' },
    ],
  },
  {
    id: 'mir',
    name: 'Mir Space Station',
    agency: 'USSR/Russia',
    type: 'Space Station',
    era: '1980s–2000s',
    destination: 'Earth Orbit',
    crewed: true,
    status: 'completed',
    launchYear: 1986,
    description: 'The first modular space station assembled in orbit, Mir hosted cosmonauts and astronauts continuously for nearly 10 years before a controlled de-orbit.',
    specs: [
      { label: 'Mass', value: '124,340 kg' },
      { label: 'Length', value: '33 m' },
      { label: 'Modules', value: '7' },
      { label: 'Crews Hosted', value: '28' },
      { label: 'Operational Life', value: '15 years' },
    ],
    funFacts: ['Valeri Polyakov spent 437 days aboard — longest single spaceflight record', 'Suffered a fire and collision during its life', 'Deorbited into the Pacific Ocean in 2001'],
    youtubeId: 'BpLthgUmxhk',
    nasaQuery: 'Mir space station Russia',
    relatedMissions: ['ISS', 'Soyuz', 'Space Shuttle'],
    timeline: [
      { year: 1986, event: 'Core module launched' },
      { year: 1994, event: 'US astronaut Shannon Lucid visits' },
      { year: 1997, event: 'Fire and collision — crisis managed' },
      { year: 2001, event: 'Controlled reentry into Pacific' },
    ],
  },
  // ESA
  {
    id: 'rosetta',
    name: 'Rosetta',
    agency: 'ESA',
    type: 'Comet Orbiter',
    era: '2000s–2010s',
    destination: 'Comet 67P',
    crewed: false,
    status: 'completed',
    launchYear: 2004,
    description: 'First spacecraft to orbit and land on a comet, releasing the Philae lander onto Comet 67P/Churyumov-Gerasimenko in November 2014.',
    specs: [
      { label: 'Mass', value: '2,900 kg' },
      { label: 'Power', value: '64 m² solar panels' },
      { label: 'Travel Distance', value: '8 billion km' },
      { label: 'Journey Duration', value: '10 years' },
    ],
    funFacts: ['Orbited comet for 2+ years', 'Philae lander bounced twice on comet surface', 'Detected organic molecules — clues to life origins'],
    youtubeId: 'D9oln7BIf68',
    nasaQuery: 'Rosetta ESA comet mission Philae',
    relatedMissions: ['Philae Lander', 'BepiColombo'],
    timeline: [
      { year: 2004, event: 'Launch' },
      { year: 2014, event: 'Reaches Comet 67P after 10-year journey' },
      { year: 2014, event: 'Philae lander deployed' },
      { year: 2016, event: 'Rosetta crashes into comet — mission ends' },
    ],
  },
  {
    id: 'solar-orbiter',
    name: 'Solar Orbiter',
    agency: 'ESA/NASA',
    type: 'Solar Observatory',
    era: '2020s–Present',
    destination: 'Sun Orbit',
    crewed: false,
    status: 'active',
    launchYear: 2020,
    description: 'Closest-ever solar observatory, taking the first images of the Sun\'s poles and studying solar wind and the heliosphere.',
    specs: [
      { label: 'Mass', value: '1,800 kg' },
      { label: 'Closest Approach', value: '42 million km from Sun' },
      { label: 'Instruments', value: '10 science instruments' },
    ],
    funFacts: ['Heat shield withstands temperatures above 500°C', 'Took first close-up images of Sun\'s south pole', 'Discovered "campfires" — small solar flares near surface'],
    youtubeId: 'YFDFDuaIpHU',
    nasaQuery: 'Solar Orbiter ESA sun images',
    relatedMissions: ['Parker Solar Probe', 'SOHO'],
    timeline: [
      { year: 2020, event: 'Launch — February 10, 2020' },
      { year: 2022, event: 'First solar perihelion pass' },
      { year: 2025, event: 'Maximum inclination over solar poles' },
    ],
  },
  // ISRO
  {
    id: 'chandrayaan3',
    name: 'Chandrayaan-3',
    agency: 'ISRO',
    type: 'Lunar Lander/Rover',
    era: '2020s',
    destination: 'Moon (South Pole)',
    crewed: false,
    status: 'completed',
    launchYear: 2023,
    description: 'India\'s historic mission that successfully landed near the lunar south pole on August 23, 2023, making India the 4th nation to land on the Moon.',
    specs: [
      { label: 'Lander Mass', value: '1,752 kg' },
      { label: 'Rover Mass', value: '26 kg (Pragyan)' },
      { label: 'Landing Site', value: '69.37°S, 32.35°E' },
      { label: 'Mission Duration', value: '1 lunar day (~14 Earth days)' },
    ],
    funFacts: ['First mission to land near lunar south pole', 'Pragyan rover detected sulfur on Moon for first time', 'Cost only ~$75 million — budget Marvel movie!'],
    youtubeId: 'IKhgmyJsG9A',
    nasaQuery: 'Chandrayaan-3 ISRO Moon landing',
    relatedMissions: ['Chandrayaan-1', 'Chandrayaan-2', 'Mangalyaan'],
    timeline: [
      { year: 2023, event: 'Launch — July 14, 2023' },
      { year: 2023, event: 'Landing near south pole — August 23, 2023' },
      { year: 2023, event: 'Pragyan rover deploys and drives' },
    ],
  },
  {
    id: 'mangalyaan',
    name: 'Mangalyaan (MOM)',
    agency: 'ISRO',
    type: 'Mars Orbiter',
    era: '2010s',
    destination: 'Mars',
    crewed: false,
    status: 'completed',
    launchYear: 2013,
    description: 'India\'s first interplanetary mission — Mars Orbiter Mission successfully entered Mars orbit in 2014 making India the first Asian nation to reach Mars.',
    specs: [
      { label: 'Mass', value: '1,337 kg' },
      { label: 'Cost', value: '$74 million (cheapest ever)' },
      { label: 'Time to Mars', value: '298 days' },
      { label: 'Orbital Period', value: '72.7 hours' },
    ],
    funFacts: ['Cheaper than Hollywood movie "Gravity" ($100M)', 'India became first Asian nation to reach Mars', 'Designed in 15 months — record speed'],
    youtubeId: 'dGPE-qYVISc',
    nasaQuery: 'Mangalyaan India Mars mission',
    relatedMissions: ['Chandrayaan-3', 'Aditya-L1'],
    timeline: [
      { year: 2013, event: 'Launch — November 5, 2013' },
      { year: 2014, event: 'Mars Orbit Insertion — September 24, 2014' },
      { year: 2022, event: 'Contact lost after 8 years' },
    ],
  },
  {
    id: 'aditya-l1',
    name: 'Aditya-L1',
    agency: 'ISRO',
    type: 'Solar Observatory',
    era: '2020s–Present',
    destination: 'L1 Lagrange Point',
    crewed: false,
    status: 'active',
    launchYear: 2023,
    description: 'India\'s first solar mission placed at the L1 Lagrange point to continuously observe the Sun and study solar corona, wind, and flares.',
    specs: [
      { label: 'Mass', value: '1,480.7 kg' },
      { label: 'Distance from Earth', value: '1.5 million km (L1)' },
      { label: 'Payloads', value: '7 instruments' },
    ],
    funFacts: ['Reached L1 after 4 months of travel', 'Named after Aditya — Sanskrit for Sun', 'Studies solar weather that affects Earth\'s technology'],
    youtubeId: 'jDUopGMFxOk',
    nasaQuery: 'Aditya L1 ISRO solar mission',
    relatedMissions: ['Mangalyaan', 'Chandrayaan-3'],
    timeline: [
      { year: 2023, event: 'Launch — September 2, 2023' },
      { year: 2024, event: 'L1 orbit insertion — January 6, 2024' },
    ],
  },
  // CNSA
  {
    id: 'tiangong',
    name: 'Tiangong Space Station',
    agency: 'CNSA',
    type: 'Space Station',
    era: '2020s–Present',
    destination: 'Earth Orbit',
    crewed: true,
    status: 'active',
    launchYear: 2021,
    description: 'China\'s permanent modular space station assembled from 2021-2022, permanently crewed by taikonauts and conducting scientific research.',
    specs: [
      { label: 'Mass', value: '~90,000 kg (complete)' },
      { label: 'Modules', value: '3 (Tianhe core + 2 labs)' },
      { label: 'Altitude', value: '~390 km' },
      { label: 'Crew Capacity', value: '3 taikonauts (up to 6 temp)' },
    ],
    funFacts: ['Assembled entirely in 1.5 years — fastest station built', 'Has robotic arm for external operations', 'Open to international scientific collaboration'],
    youtubeId: 'Cb2U14UXtd0',
    nasaQuery: 'Tiangong China space station',
    relatedMissions: ['Shenzhou', 'Tianhe', 'Wentian'],
    timeline: [
      { year: 2021, event: 'Tianhe core module launched' },
      { year: 2022, event: 'Station assembly complete' },
      { year: 2024, event: 'Ongoing operations with rotating crews' },
    ],
  },
  {
    id: 'tianwen1',
    name: 'Tianwen-1',
    agency: 'CNSA',
    type: 'Mars Orbiter/Rover',
    era: '2020s',
    destination: 'Mars',
    crewed: false,
    status: 'completed',
    launchYear: 2020,
    description: 'China\'s first independent Mars mission with orbiter, lander, and Zhurong rover. China became only 2nd nation to successfully land a rover on Mars.',
    specs: [
      { label: 'Orbiter Mass', value: '3,175 kg' },
      { label: 'Zhurong Rover Mass', value: '240 kg' },
      { label: 'Landing Site', value: 'Utopia Planitia' },
    ],
    funFacts: ['First mission to simultaneously orbit, land, and rove Mars', 'Zhurong rover has solar panels unlike nuclear-powered US rovers', 'Detected subsurface water ice evidence'],
    youtubeId: 'G9-VfTm5aRc',
    nasaQuery: 'Tianwen-1 China Mars Zhurong rover',
    relatedMissions: ['Tiangong', 'Chang\'e missions'],
    timeline: [
      { year: 2020, event: 'Launch — July 23, 2020' },
      { year: 2021, event: 'Mars orbit insertion' },
      { year: 2021, event: 'Zhurong rover lands in Utopia Planitia' },
    ],
  },
  // JAXA
  {
    id: 'hayabusa2',
    name: 'Hayabusa2',
    agency: 'JAXA',
    type: 'Asteroid Sample Return',
    era: '2010s–2020s',
    destination: 'Asteroid Ryugu',
    crewed: false,
    status: 'completed',
    launchYear: 2014,
    description: 'Collected samples from asteroid Ryugu and returned them to Earth in 2020. Analysis revealed complex organic molecules — possible ingredients for life.',
    specs: [
      { label: 'Mass', value: '608 kg' },
      { label: 'Sample Collected', value: '5.4 grams from Ryugu' },
      { label: 'Journey Duration', value: '6 years round trip' },
    ],
    funFacts: ['Shot a copper bullet into asteroid to create artificial crater', 'Collected samples from both surface and crater', 'Found amino acids — building blocks of life'],
    youtubeId: 'OMf4IbZOK7Q',
    nasaQuery: 'Hayabusa2 asteroid Ryugu sample',
    relatedMissions: ['Hayabusa 1', 'OSIRIS-REx'],
    timeline: [
      { year: 2014, event: 'Launch' },
      { year: 2018, event: 'Arrives at Ryugu' },
      { year: 2019, event: 'Sample collection and crater creation' },
      { year: 2020, event: 'Sample capsule returned to Earth' },
    ],
  },
  // Private
  {
    id: 'falcon9',
    name: 'Falcon 9',
    agency: 'SpaceX',
    type: 'Launch Vehicle',
    era: '2010s–Present',
    destination: 'Earth Orbit/ISS',
    crewed: false,
    status: 'active',
    launchYear: 2010,
    description: 'The world\'s most frequently flown orbital rocket with a reusable first stage that lands and refliesRevolutionized launch costs and frequency.',
    specs: [
      { label: 'Height', value: '70 m' },
      { label: 'Diameter', value: '3.66 m' },
      { label: 'Mass', value: '549,054 kg' },
      { label: 'Payload to LEO', value: '22,800 kg' },
      { label: 'Booster Reflights', value: '20+ per booster' },
    ],
    funFacts: ['First orbital rocket to land its first stage on a drone ship', 'Has flown 250+ missions', 'Reduced launch costs by 10x compared to predecessors'],
    youtubeId: 'ANv5UfZsvZQ',
    nasaQuery: 'SpaceX Falcon 9 booster landing',
    relatedMissions: ['Falcon Heavy', 'Starship', 'Crew Dragon'],
    timeline: [
      { year: 2010, event: 'First flight' },
      { year: 2015, event: 'First successful booster landing' },
      { year: 2017, event: 'First reused booster' },
      { year: 2024, event: '300th mission milestone' },
    ],
  },
  {
    id: 'starship',
    name: 'Starship',
    agency: 'SpaceX',
    type: 'Super Heavy Launch Vehicle',
    era: '2020s–Present',
    destination: 'Moon/Mars/Beyond',
    crewed: true,
    status: 'active',
    launchYear: 2023,
    description: 'Tallest and most powerful rocket ever built, designed for full reusability and eventual human missions to Mars. Selected for NASA Artemis Moon landings.',
    specs: [
      { label: 'Height', value: '121 m (fully stacked)' },
      { label: 'Diameter', value: '9 m' },
      { label: 'Mass', value: '5,000,000 kg' },
      { label: 'Payload to LEO', value: '150,000 kg (reusable)' },
      { label: 'Thrust', value: '74.4 MN (33 Raptor engines)' },
    ],
    funFacts: ['More thrust than 10 Saturn V rockets combined', 'Aims to be fully reusable including the booster', 'Selected by NASA to land astronauts on Moon for Artemis'],
    youtubeId: 'z1jQHxLJYLg',
    nasaQuery: 'SpaceX Starship launch test',
    relatedMissions: ['Falcon 9', 'Falcon Heavy', 'Artemis'],
    timeline: [
      { year: 2019, event: 'Starhopper tests begin' },
      { year: 2023, event: 'First integrated test flight' },
      { year: 2024, event: 'Successful catch of Super Heavy booster' },
    ],
  },
  // Other Nations
  {
    id: 'hope',
    name: 'Hope Mars Mission',
    agency: 'UAE Space Agency',
    type: 'Mars Orbiter',
    era: '2020s',
    destination: 'Mars',
    crewed: false,
    status: 'active',
    launchYear: 2020,
    description: 'UAE\'s first interplanetary mission and the Arab world\'s first Mars mission. Studies Martian atmosphere and climate to understand water loss.',
    specs: [
      { label: 'Mass', value: '1,350 kg' },
      { label: 'Orbital Period', value: '55 hours' },
      { label: 'Instruments', value: '3 science instruments' },
    ],
    funFacts: ['First Arab interplanetary mission', 'Named "Al-Amal" (Hope) in Arabic', 'Arrived at Mars on UAE National Day in 2021'],
    youtubeId: 'mK1h8BqGvFU',
    nasaQuery: 'Hope mission UAE Mars orbit',
    relatedMissions: ['Mangalyaan', 'Tianwen-1'],
    timeline: [
      { year: 2020, event: 'Launch from Japan' },
      { year: 2021, event: 'Mars orbit insertion — February 9, 2021' },
    ],
  },
];
